services:
  app:
    build: .
    container_name: czk_sync_service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/config.yaml:/app/app/config.yaml
    restart: unless-stopped
